### ISSUE TITLE
Jpeg writer false colors

### ISSUE THREAD

**Issue by alexkazik** [lehins/hip#11]
When loading a png image and storing it as a jpeg results in false colors.
Writing as png is fine.

Command: `readImageRGB VU "in.png" >>= writeImage "out.jpg"`
Example image: [images.zip](https://github.com/lehins/hip/files/815267/images.zip)

**Comment by lehins** [comment]
Both images in the archive look exactly the same. Can you includse the name of the image viewer you are using and your system OS? Even if there is some sort of encoding issue, it is likely a problem upstream in JuicyPixels library. Since I cannot replicate the issue, do you mind trying using JuicyPixels directly.

**Comment by lehins** [comment]
Here is a snippet you can run to validate if there is a bug in JuicyPixels or there is something going on inside hip:
```
#!/usr/bin/env stack
-- stack exec --resolver lts-8.2 --package JuicyPixels-- ghc -O2

import qualified Data.ByteString.Lazy as S (writeFile)
import Codec.Picture
import Codec.Picture.Types

main :: IO ()
main = do
  Right (ImageRGB8 img) <- readImage "in.png"
  S.writeFile "out.jpeg" $ encodeJpegAtQuality 100 $ convertImage img
```

**Comment by lehins** [comment]
@alexkazik, let me know what will be the outcome. Thank you for reporting those issues.

**Comment by alexkazik** [comment]
In JuicyPixels (lts-8.0, same as hip) everything was ok.

I've opened the image in the Mac OS included viewers and with Adobe Photoshop Express:
![both](https://cloud.githubusercontent.com/assets/612453/23531535/2211efca-ffa7-11e6-8be8-b9212d02051f.jpg)

**Comment by lehins** [comment]
As I suspected the bug is in fact in JuicyPixels library. In order to reproduce it:

```haskell
#!/usr/bin/env stack
-- stack exec --resolver lts-8.2 --package JuicyPixels-- ghc -O2

import qualified Data.ByteString.Lazy as S (writeFile)
import Codec.Picture
import Codec.Picture.Types
import Codec.Picture.Jpg

main :: IO ()
main = do
  Right (ImageRGB8 imgRGB) <- readImage "in.png"
  S.writeFile "out.jpeg" $ encodeDirectJpegAtQualityWithMetadata 100 mempty imgRGB
```

The actual bug shows up when jpeg image is being saved in RGB8 color space (resulting image is 80k too). In [a previous snippet](https://github.com/lehins/hip/issues/11#issuecomment-283812181) it was explicitly converted to YCbCr8, which works as expected.

In order to avoid this bug in HIP library, image needs to be also explicitly converted to `YCbCr` color space:

```haskell
import Graphics.Image as I
import Graphics.Image.Interface as I

hipConvert2Jpeg :: FilePath -> FilePath -> IO (Image VS YCbCr Word8)
hipConvert2Jpeg fpIn fpOut = do
  imgRGB <- readImageRGB VS fpIn
  let imgYCbCrHIP = I.map (fmap toWord8) $ toImageYCbCr imgRGB
  writeImageExact JPG [] fpOut $ imgYCbCrHIP
  return imgYCbCrHIP
```

On that note, it would be nice for this issue to be fixed upstream. Unfortunately I don't have a Windows or Mac system around, hence I don't have Adobe Photoshop either. I've checked images produced in various viewers (GIMP, ImageMagick, Feh, GPicView, ShotwellViewer, eog, Firefox, Chrome) and none of them had false colors. Granted images produced were bigger in size, but that's just the nature of RGB vs YCbCr for JPEGs. So, as far as I can tell it smells more like a bug in Adobe Photoshop to me, but who am I to judge.
 @alexkazik, I would really appreciate if you could confirm my hypothesis of the origin of the bug and possibly open an issue in [JuicyPixels](https://github.com/Twinside/Juicy.Pixels/issues/new) library. 

I do appreciate you reporting this issue, and if you find my hypothesis to be incorrect and workaround I mentioned still produces false colors, feel free to reopen this issue. On my side I will make `YCbCr` to be a default color space for `JPG` images, as it should have been from the beginning, which will make `writeImage` produce proper JPEGs.

**Comment by alexkazik** [comment]
I thought that all jpegs are in YCbCr (except for those in CMYK).
The workaround does work well.

Chrome is also correct so far only Photoshop Express and the views built in to Mac OS are showing (the same) false colors.

When I open it in GIMP I get the error message "Corrupt JPEG data: premature end of data segment" bur displays it correct.

I'll open an issue in JuicyPixels.
