### ISSUE TITLE
Parentheses error in makeImageR documentation

### ISSUE THREAD

**Issue by ChaiTRex** [lehins/hip#32]
I was helping someone with an error they experienced and it seems that in [`Graphics.Image.makeImageR`'s documentation](http://hackage.haskell.org/package/hip-1.5.3.0/docs/Graphics-Image.html#v:makeImageR), there may be a parentheses error:

    let grad_gray = makeImageR RPU (200, 200) (\(i, j) -> PixelY $ fromIntegral (i*j)) / (200*200)

I believe it should be:

    let grad_gray = makeImageR RPU (200, 200) (\(i, j) -> PixelY $ fromIntegral (i*j) / (200*200))

This way the division by `(200*200)` is within the lambda.

---

Also, the type may need to be specified (*i*.*e*., `(200*200 :: Double)`), I'm not sure.

**Comment by lehins** [comment]
The parenthesis are placed correctly, the problem you might be having is probably because the compiler cannot infer the proper type for the pixel (Double), but there is no mistake in the example and is in fact intentional. `Image` has an instance of `Num`, so the example in the documentation is actually translated to something like that:
```haskell
let grad_gray = zipWith (/) (makeImageR RPU (200, 200) (\(i, j) -> PixelY $ fromIntegral (i*j)))
                            (zipWith (*) (fromIntegral 200 :: Image Y Double) (fromIntegral 200 :: Image Y Double))
```
This fact is explicitly documented right above the example:
> Because all Pixels and Images are installed into Num, above is equivalent to:

That being said, what you suggested would work too and is in fact equivalent. Feel free to reopen this ticket if you still having trouble.

**Comment by lehins** [comment]
@ChaiTRex I update the example in haddock, so in no longer produces results in an inference error. Thanks for reporting this problem ;)
