### ISSUE TITLE
writeImage only works with images using Double

### ISSUE THREAD

**Issue by Purrlite** [lehins/hip#9]
If I write something like:

```
λ let image = makeImage (512,512) (const (PixelRGB 10 10 10)) :: Image VS RGB Word8
λ writeImage "test.png" image
```

then I get a compile error, saying that there is no instance of Writable in this case. However if I instead use writeImageExact for the same purpose, it works fine.

**Comment by lehins** [comment]
Yes, you are absolutely correct. This behavior is documented under `writeImage`, and it is a convenience function that will do all implicit precision and color space conversions while encoding an image, thus making it possible to save an image with `Double` precision and `Y`, `YA` `RGB` and `RGBA` color spaces into any supported format. Adding ability to save an image with other precision types like `Word8`, `Word16`, etc. using `writeImage` would also require an implicit conversion, for instance:
```
λ let image = makeImage (512,512) (const (PixelRGB 10 10 10)) :: Image VS RGB Word16
λ writeImage "test.jpg" image
```
would require dropping precision down to `Word8` and converting to `YCbCr` color space (which is a bit complicated to do if it's not `Double`) prior to saving this image. Taking into account the number of supported color spaces and possible precision types I am not sure it would be feasible to implement all of those implicit conversions. That is the reason for `writeImageExact`, which will save an image in exact color space and precision image is in.

I'll keep this ticket open for now. Maybe having a very smart function that will be able to write any image type into all supported image files would be desired, but I'd vote against it.

**Comment by Purrlite** [comment]
Ah, that makes sense. I guess I just forgot about that part of the documentation.

Could you maybe make another convenience function that works like `writeImageExact`, but doesn't have the two first arguments (it would just guess the file extension in the same way `writeImage` does). I would find that really useful and it's kind of what I was trying to use the `writeImage` function for.

**Comment by lehins** [comment]
@Purrlite Yeah, I agree, this sort of function would be nice. Unfortunately, it's not possible. When calling a function like `writeImage`, and you don't know ahead of time the file format of the image it should be saved in (i.e. would like to guess it at runtime from a file extension), this function must know how to convert this image to all supported image formats, which is why it is currently possible only for `Y` and `RGB` images with `Double` precision. The ways to make image encoding work are:
* either to have functions like `writePngImage` functions, which is what JuicyPixels does
* supply image format type as an argument, which is what `writeImageExact` does
* or implement conversion for all possible image formats, as I described in a previous comment.

If you have any ideas on how to implement this kind of behavior in some easy fashion, please let me know or even better, send a PR. :) Improvements are always welcomed.

**Comment by Purrlite** [comment]
Ahh, I didn't know that. Thank you for the explanation.
